### ISSUE TITLE
On some devices widget goes crazy :)

### ISSUE THREAD

**Issue by ProgrammingLife** [kherel/reviews_slider#1]
I use 1280x800 screen resolution (ppi 1:1) without Scaffold-widget. If I set padding to 0 it draws "Great"-smile out of the screen but I suppose it should draw all the images inside the screen.

And the second bug appears on the wide size of ReviewSlider-widget. When you drag the face and follow at the right place (at the center of moving face) when your finger is near the Terrible-value and then the face fly away from your finger when you drag it to Great-value.

**Comment by kherel** [comment]
Oh. I didn't expect that someone would be using it. Thanks for the interest.
I'll check it next few days.

**Comment by ProgrammingLife** [comment]
I think ReviewSlider gets the whole width of the screen. It would be better if ReviewSlider took a width of a parent widget in which it is placed. If it's possible, of course :)

**Comment by kherel** [comment]
Hi, I've made a package https://pub.dev/packages/reviews_slider and hopfully fixed the problem. Could you check it?

**Comment by ProgrammingLife** [comment]
It's much better now! Now it follows my finger perfectly!

As of next improvements I think all those sizes should inherit from some settings which we will pass with the init:
https://github.com/kherel/reviews_slider/blob/master/lib/reviews_slider.dart#L165
because all devices have their own resolution, ppi (retinas or others), etc. On some of them we need to have bigger size of widget, on others - less :)

It's really good idea of a review indicator!

**Comment by kherel** [comment]
thank you.
I'll think about your suggestion and try to implement it in next few weeks 😉
